news:
  url: ${NEWS_URL:https://api.apilayer.com/financelayer/news}
  key: ${NEWS_KEY:8834a53d7937fb35293619382c579b95b815e0b264676148a032f5f63cc5e6091fdcf4535171e2f451400f724cfcb616cb68acdcac8f1727312fd230de82fefe
currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  key: ${API_KEY:8834a53d7937fb35293619382c579b95b815e0b264676148a032f5f63cc5e6091fdcf4535171e2f451400f724cfcb616cb68acdcac8f1727312fd230de82fefe
server:
  port: {cipher}8377a5d1d950df96a118445e87e58c94be02c89dca2f85db6268debe442005b9

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5431/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter
keycloak:
  auth-server-url: http://172.18.11.111:8081
  autodetect-bearer-only:  true
  credentials:
    secret: rHQt08HXef8oRlgXRhjB2Q2qW99GdjgX
  realm: software
  ssl-required: none
  resource: backend
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: ADMINISTRADOR
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/currency/list
    - auth-roles:
        - USER
      security-collections:
        - name: USER
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/currency/exchange
management:
  endpoints:
    web:
      exposure:
        include: "*"
